libraryRoot: "/data"
# listingPath: "/data/listing.txt"
# librarySongsDir: "/data/uriminzokkiri"
port: 3000
reindexToken: "change-me"
# cacheDir: "/app/cache"
# appOrigin: "http://localhost:8080"
playlistsDir: "/app/data/playlists"
titleMetadataPath: "/config/title-metadata.json"
titleLanguage: "en"
